### ISSUE TITLE
Graceful handling of git errors

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#104]
When git isn't installed:

```
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/vagrant/needy/scripts/needy", line 9, in <module>
    sys.exit(main(sys.argv))
  File "/vagrant/needy/needy/__main__.py", line 275, in main
    return commands[parameters.command](parameters.args)
  File "/vagrant/needy/needy/__main__.py", line 77, in satisfy
    needy.satisfy_target(needy.target(parameters.target), parameters.library)
  File "/vagrant/needy/needy/needy.py", line 352, in satisfy_target
    library.build()
  File "/vagrant/needy/needy/library.py", line 115, in build
    self.clean_source()
  File "/vagrant/needy/needy/library.py", line 101, in clean_source
    source.clean()
  File "/vagrant/needy/needy/sources/git.py", line 21, in clean
    command(['git', 'clean', '-xfd'], logging.DEBUG)
  File "/vagrant/needy/needy/process.py", line 37, in command
    __log_check_call(cmd, verbosity, env=env)
  File "/vagrant/needy/needy/process.py", line 28, in __log_check_call
    subprocess.check_call(cmd, stderr=devnull, shell=shell, stdout=devnull, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by vmrob** [comment]
And it should probably also error out when the remote host isn't recognized:

```
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by ccbrown** [comment]
Consolidating into #106
